### ISSUE TITLE
sbt assembly error

### ISSUE THREAD

**Issue by yuchaoran2011** [databricks/learning-spark#4]
After running "sbt assembly", I got the following error:

[error] learning-spark/src/main/scala/com/oreilly/learningsparkexamples/scala/BasicParseJsonWithJackson.scala:47: not found: type ioRecord
[error]             Some(mapper.readValue(record, classOf[ioRecord]))
[error]                                                   ^
[error] learning-spark/src/main/scala/com/oreilly/learningsparkexamples/scala/BasicParseJsonWithJackson.scala:53: value lovesPandas is not a member of Nothing
[error]     result.filter(_.lovesPandas).map(mapper.writeValueAsString(_))
[error]                     ^
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 24 s, completed Jun 17, 2015 10:00:31 PM

Removing BasicParseJsonWithJackson.scala and recompiling would result in other errors related to protocol buffer. Has anyone successfully built the project? How did you do it?

Thanks!

**Comment by holdenk** [comment]
So its currently passing in travis, do you have the protocol buffer complier installed? Could you post the full log of your error?

**Comment by yuchaoran2011** [comment]
Thanks for your reply. I'm running the build on a mac. I think I have protocol buffer compiler installed. Running "protoc --version" gave me "libprotoc 3.0.0".

The full log after I typed "sbt assembly" is as follows:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[info] Loading project definition from /Users/stephen/Desktop/learning-spark/project
[info] Updating {file:/Users/stephen/Desktop/learning-spark/project/}learning-spark-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-14d4d23e25f354cd296c73bfff40554[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to learning-spark-examples (in build file:/Users/stephen/Desktop/learning-spark/)
[info] Updating {file:/Users/stephen/Desktop/learning-spark/}learning-spark...
[info] Resolving com.sun.jersey.jersey-test-framework#jersey-test-framework-griz[info] Resol[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.hadoop.gplcompression:hadoop-lzo:0.4.17 -> 0.4.19
[warn] 	* com.fasterxml.jackson.module:jackson-module-scala_2.10:2.3.3 -> 2.4.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 2 protobuf files to /Users/stephen/Desktop/learning-spark/target/scala-2.10/src_managed/main/compiled_protobuf
[info] Compiling schema /Users/stephen/Desktop/learning-spark/src/main/protobuf/address_book.proto
[info] Compiling schema /Users/stephen/Desktop/learning-spark/src/main/protobuf/places.proto
[error] [libprotobuf WARNING google/protobuf/compiler/parser.cc:491] No syntax specified for the proto file. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[error] [libprotobuf WARNING google/protobuf/compiler/parser.cc:491] No syntax specified for the proto file. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[info] Compiling protobuf
[info] Protoc target directory: /Users/stephen/Desktop/learning-spark/target/scala-2.10/src_managed/main/compiled_protobuf
[info] Compiling 43 Scala sources and 40 Java sources to /Users/stephen/Desktop/learning-spark/target/scala-2.10/classes...
[error] /Users/stephen/Desktop/learning-spark/src/main/scala/com/oreilly/learningsparkexamples/scala/BasicParseJsonWithJackson.scala:47: not found: type ioRecord
[error]             Some(mapper.readValue(record, classOf[ioRecord]))
[error]                                                   ^
[error] /Users/stephen/Desktop/learning-spark/src/main/scala/com/oreilly/learningsparkexamples/scala/BasicParseJsonWithJackson.scala:53: value lovesPandas is not a member of Nothing
[error]     result.filter(_.lovesPandas).map(mapper.writeValueAsString(_))
[error]                     ^
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 26 s, completed Jun 21, 2015 12:10:34 AM

Thank you!

**Comment by neilkdev** [comment]
It is failing in travis as well.

**Comment by holdenk** [comment]
The last build in travis was green, https://travis-ci.org/holdenk/learning-spark-examples/builds , but I'll kick of a new build now.

**Comment by neilkdev** [comment]
If I remove the BasicParseJsonWithJackson.scala file, build is successful using SBT.
However, Maven build is successful without any changes.

**Comment by kevinpauli** [comment]
Same is happening to me.  I'm using OSX Mavericks, and protobuf installed with homebrew.

**Comment by holdenk** [comment]
@kevinpauli thanks, I'll take a look at the sbt version.

**Comment by wenwenlin** [comment]
@yuchaoran2011 hi, have you solve it?

**Comment by yuchaoran2011** [comment]
@wenwenlin No. I just kept reading and trying out code in REPL. Will probably get back to it in the future or when somebody here comes up with a solution.

**Comment by holdenk** [comment]
It seems that the databricks repo and my repo diverged (and this error was introduced in the databricks repo). Quite likely my fault. I've updated both and fixed the issue.

**Comment by eduardomiranda** [comment]
I just cloned the repo, ran ./sbt/sbt assembly and I am getting the same errors:

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  \* com.hadoop.gplcompression:hadoop-lzo:0.4.17 -> 0.4.19
[warn]  \* com.fasterxml.jackson.module:jackson-module-scala_2.10:2.3.3 -> 2.4.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 2 protobuf files to /home/emiranda/Desktop/learning-spark/target/scala-2.10/src_managed/main/compiled_protobuf
[info] Compiling schema /home/emiranda/Desktop/learning-spark/src/main/protobuf/places.proto
[info] Compiling schema /home/emiranda/Desktop/learning-spark/src/main/protobuf/address_book.proto
java.lang.RuntimeException: error occured while compiling protobuf files: Cannot run program "protoc": error=2, No such file or directory

 Any idea on how I can work-around that?

**Comment by Heipiao** [comment]
`sudo apt-get install libprotobuf-dev protobuf-compiler`
it work for me
