### ISSUE TITLE
sbt assembly error

### ISSUE THREAD

**Issue by dheinz** [databricks/learning-spark#6]
I downloaded the usb.zip and am following the OReilly video course Introduction to Apache Spark.   There are some places where the presentation is out of sync with the usb.zip contents but this is where it really hurts - I cant seem to compile the examples with the instruction provided in the video, that is, run the sbt.cmd file with the parameter assembly.  Is there a fix for this?  This is the error I get.

D:\Spark\usb\spark-training\sbt>sbt assembly
[info] Set current project to sbt (in build file:/D:/Spark/usb/spark-training/sbt/)
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] assembly
[error]         ^

D:\Spark\usb\spark-training\sbt>

**Comment by holdenk** [comment]
These are the examples from the book, I think this is unrelated.
