### ISSUE TITLE
Manually adding scala.binary.version to Maven pom file

### ISSUE THREAD

**Issue by shimizust** [databricks/learning-spark#9]
I had an issue during building the project due to missing property: scala.binary.version, which is used for:

````
<dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest_${scala.binary.version}</artifactId>
      <version>2.2.1</version>
</dependency>
````

The property doesn't appear to be set in the pom file. I fixed the issue by adding my Scala version. Should this be added by default? I didn't see any documentation that this needs to be set, or am I doing it wrong?:

````
<properties>
    <java.version>1.7</java.version>
    <scala.binary.version>2.10</scala.binary.version>
 </properties>
````

**Comment by holdenk** [comment]
Thanks for the fix
